### ISSUE TITLE
Test xblock-drag-and-drop-v2 on Python 3.11

### ISSUE THREAD

**Issue by feanil** [openedx/xblock-drag-and-drop-v2#398]
This repository is a depedency of edx-platform and needs to be upgraded to Python 3.11 before
the Readwood release is cut (mid-April).

- [ ] Requirements are compiled with Python 3.8
- [ ] Tests are run on Python 3.8 and 3.11
- [ ] (Optional) Tests are also run with 3.12 and passing or 3.12 issues are ticketed.
- [ ] Classifiers in setup.py setup.cfg or pyproject.toml indicate Python 3.11 support
- [ ] A new version is release to PyPI
- [ ] A PR is merged to edx-platform to use the new version

**Comment by Agrendalath** [comment]
@feanil, I completed all the steps except for the last one. The version in `edx-platform` should be automatically updated by the requirements bot, right?

**Comment by feanil** [comment]
Thanks @Agrendalath, yea the automation did pick this up.
