### ISSUE TITLE
can't change the image

### ISSUE THREAD

**Issue by nlhsueh** [openedx/xblock-drag-and-drop-v2#99]
can't change the image. when I set an image, for example
/static/map.jpg

and click "change image"

it will leave the setting.

When I set the URL, it does not work, either.

![image](https://cloud.githubusercontent.com/assets/5356603/18117129/41e7fbe0-6f7f-11e6-9c94-022447f60ead.png)

**Comment by e-kolpakov** [comment]
@nlhsueh Hi! Are there any other relevant information you could share (i.e. errors in Studio logs, errors in browser console, etc.)? What DnDv2 version do you use?

**Comment by e-kolpakov** [comment]
@nlhsueh Have you resolved the problem?
